### ISSUE TITLE
Unable to run module.py script after 1.1.1 update

### ISSUE THREAD

**Issue by jrnelson90** [BlokasLabs/patchbox-cli#5]
https://github.com/BlokasLabs/patchbox-cli/blob/80718498f4f0cdc1b0f2f9e3e1dd8c12738cae0a/patchbox/module.py#L227

I was only able to install Modep by not updating to 1.1.1 first. Installing updates first results in an error thrown at the line mentioned above.

I can see that in the full trace it is still mentioning v1.0

**Comment by gtrainavicius** [comment]
Thank you for reporting this, we've just released a fix in 1.1.2 version, you may get it either through `patchbox`->`update` option or the classic `sudo apt update && sudo apt install patchbox-cli`. :)

Cheers!
