### ISSUE TITLE
Error running module.py via wizard after applying 1.1.1 patchbox-cli update on fresh install

### ISSUE THREAD

**Issue by jrnelson90** [BlokasLabs/patchbox-cli#6]
https://github.com/BlokasLabs/patchbox-cli/blob/80718498f4f0cdc1b0f2f9e3e1dd8c12738cae0a/patchbox/module.py#L227

I was only able to install Modep by not updating to 1.1.1 first. Installing updates first results in an error thrown at the line mentioned above.

I can see that in the full trace it is still mentioning v1.0

**Comment by jrnelson90** [comment]
sorry for the double issue post, GitHub was 504-ing there for a moment and I didn't realize the first one had actually gone through

**Comment by gtrainavicius** [comment]
Hey, no problem, we'll look into the issue and we'll continue tracking this issue in #5, closing this one. :)
